#!/bin/bash

[ -r "/var/run/elmlinkd/.index" ] || exit 0

UART_INFO=$(egrep ^UART /var/run/elmlinkd/.index | cut -d' ' -f2,3)
CHANNEL=$(egrep '^CHANNEL ([0-9]+) quiesce$' /var/run/elmlinkd/.index | cut -d' ' -f2)
/usr/libexec/elmlink-lowlevel-send $UART_INFO $CHANNEL 0x51 0x55 0x49 0x45 0x53 0x43 0x45 0x5f 0x43 0x4f 0x4d 0x50 0x4c 0x45 0x54 0x45
exit 0
